services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: agendamento-backend-prod
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "10.10.10.3:8001:8001"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
    networks:
      - agendaprame

networks:
  agendaprame:
    driver: bridge
